### ISSUE TITLE
Time format is broken. 07:24 instead of 19:24

### ISSUE THREAD

**Issue by nicosayer** [neoPix/attest-fr-covid#1]
@neoPix Thanks for the repo !

I believe, the time format should be `HHmm` instead of `hhmmA` if you want it to stick with the original certificate generator. 

https://github.com/neoPix/attest-fr-covid/blob/327541f52fe55817ae547f8b7afd62f8af0390af/lib/index.ts#L38

**Comment by neoPix** [comment]
Hi,
![Screenshot from 2020-11-10 10-49-53](https://user-images.githubusercontent.com/8171264/98657789-89b3ae80-2342-11eb-8752-8dab4640623a.png)

**Comment by neoPix** [comment]
Hi,

thanks for the feedback,

I'm currently looking into this. Here is the display I get on my laptop, probably linked to my `en` environment configuration.

![Screenshot from 2020-11-10 10-49-53](https://user-images.githubusercontent.com/8171264/98657828-97693400-2342-11eb-926b-267a09434a23.png)

**Comment by neoPix** [comment]
Found a way to circumvent this format issue: https://github.com/neoPix/attest-fr-covid/commit/2db40cf057f34095df3de074b70c8b4f7ef9ffef

Will update the NPM package soon.

**Comment by neoPix** [comment]
Fixed in `V1.1.1` https://github.com/neoPix/attest-fr-covid/tree/v1.1.1
